### ISSUE TITLE
Where is previous oracle database?

### ISSUE THREAD

**Issue by zidekuls** [zzzprojects/sqlfiddle4#2]
There was oracle 11g in previous sqlfiddle, now it disappear...

**Comment by JonathanMagnan** [comment]
Hello @zidekuls ,

We now rely on a third-party API to execute SQL queries, which means we don't have control over when Oracle support will be reinstated.

When the new version of SQL Fiddle becomes more stable (a lot of changes is coming every week), we will surely contact them and work with them to make it happen but meanwhile, only the Chat and Editor for Oracle is available: https://sqlfiddle.com/oracle/online-compiler

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @zidekuls ,

For your info, SQL Fiddle now support [Oracle](https://sqlfiddle.com/oracle/online-compiler) and [Oracle PLSQL](https://sqlfiddle.com/oracle-plsql/online-compiler)

Best Regards,

Jon
